name = "gittensor-meta-injector"
main = "cloudflare-worker-meta-injector.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "test.gittensor.io/*"
zone_name = "gittensor.io"

[[routes]]
pattern = "gittensor.io/*"
zone_name = "gittensor.io"

